### ISSUE TITLE
Feature Request: Ability to disable slash commands

### ISSUE THREAD

**Issue by bennyandresen** [rlhk/logseq-url-plus#13]
Cool project!

For example I'm never interested in certain slash commands and would like if they don't show up when I type `/URL+` so filtering means I'm able to find the correct entry with fewer keystrokes.

TIA

**Comment by rlhk** [comment]
You don't need to start typing with `URL+`. Say if you'd like to access `URL+ [title](url)`, you could simply type `/title` and the command will show up in a list for your selection. Does this solve the issue?

**Comment by bennyandresen** [comment]
Fair enough. You can consider this issue closed.

Would you however accept a PR to have entries in the settings so they can be individually enabled and disabled, just because of a potential cluttering of the global slash-command-namespace?

**Comment by rlhk** [comment]
Yes. Would love such PR!
Since it's related to this issue. Let's keep it open for the PR.
