### ISSUE TITLE
quote title and description text

### ISSUE THREAD

**Issue by Bad3r** [rlhk/logseq-url-plus#16]
If the link title or description contains special symbols like `#,` they get parsed as logseq tags and not a string of text. 

This issue could be resolved by quoting the title and header. 
Example test case:
https://www.youtube.com/watch?v=qW96515QG6Y

Parse it with URL+ metadata -> Logseq attributes, and note the title.

Sidenote: could the order of description and title be swapped? It doesn't make sense that the title is under the description.

**Comment by rlhk** [comment]
Shall take a look.
BTW, the attributes order is determined by the returned result. Custom order probably another bigger feature.

**Comment by rlhk** [comment]
Second thought, rendering markdown in attribute string seems to be an incidental feature to me. Say you could insert valid link `[[xxx]]` as well. I'm not sure how often do you encounter attribute string with `#`. Would it be easier to just edit?

**Comment by Bad3r** [comment]
yeah good call
